name: CI/CD
on:
  workflow_dispatch:
  push:
    branches: ['master']

env:
    IMAGE_TAG: ${{ github.run_number }}
    REGISTRY: registry.cn-zhangjiakou.aliyuncs.com/baiyigali/osssync
    REGISTRY_USERNAME: ${{ vars.REGISTRY_USERNAME }}
    REGISTRY_PASSWORD: ${{ secrets.REGISTRY_PASSWORD }}
    
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Login to ACR
      run: docker login -u $REGISTRY_USERNAME -p $REGISTRY_PASSWORD $REGISTRY

    - name: Build image
      run: docker build -t $REGISTRY:$IMAGE_TAG .

    - name: Push image
      run: docker push $REGISTRY:$IMAGE_TAG
